### ISSUE TITLE
Getting Unexpected token ? error

### ISSUE THREAD

**Issue by RR-28023** [gavinr/github-csv-tools#106]
Hi! Thanks for publishing this tool.

Tried to use it for the first time and getting this error:

```
> githubCsvTools auto_issues_creation.csv
/usr/local/lib/node_modules/github-csv-tools/node_modules/json-2-csv/lib/converter.js:9
    const builtOptions = (0, utils_1.buildJ2COptions)(options ?? {});
                                                               ^

SyntaxError: Unexpected token ?
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/github-csv-tools/export.js:2:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
```
I'm running it on `Ubuntu 20.04.5 LTS`.

Any clue on what I may be missing? Thanks

**Comment by RR-28023** [comment]
Actually, I'm seeing that I get the same error if I simply run `githubCsvTools --help`, so it might be an installation issue.

**Comment by RR-28023** [comment]
It seems it was an issue with my `npm`not being properly installed. Closing the issue
