### ISSUE TITLE
 Resource not accessible by personal access token

### ISSUE THREAD

**Issue by makahmad** [gavinr/github-csv-tools#109]
githubCsvTools version 3.2.0

and node v18.18.0

I'm trying to create issues for an organization. I made sure that "Fine-grained personal access tokens" Allow access is on and I'm the administrator too. however I'm still getting " Resource not accessible by personal access token" error

```
githubCsvTools aeps.csv
Token (get from https://github.com/settings/tokens): [ENTERED TOKEN HERE]
User or organization: aep-dev
Repository: aep.dev
[@octokit/plugin-throttling] `onAbuseLimit()` is deprecated and will be removed in a future release of `@octokit/plugin-throttling`, please use the `onSecondaryRateLimit` handler instead
Error
RequestError [HttpError]: Resource not accessible by personal access token
    at /usr/local/lib/node_modules/github-csv-tools/node_modules/@octokit/request/dist-node/index.js:122:21
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Job.doExecute (/usr/local/lib/node_modules/github-csv-tools/node_modules/bottleneck/light.js:405:18) {
  status: 403,
  response: {
    url: 'https://api.github.com/repos/aep-dev/aep.dev/import/issues',
    status: 403,
    headers: {

```

**Comment by nguyentoanit** [comment]
I got same issue here. Any suggestion?

**Comment by jack-collier-prepmd** [comment]
The request's [Accept header needs to have](https://gist.github.com/jonmagic/5282384165e0f86ef105#general-notes) `application/vnd.github.golden-comet-preview`, which I don't see in the debug info.

Could that be the issue?
